apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
  namespace: so1-fase2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: docker.io/ifigueroa065/api-node-metrics:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: node-api-db-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: node-api-db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: node-api-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: node-api-db-secret
              key: DB_NAME
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  namespace: so1-fase2
spec:
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
