apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-socket
  namespace: so1-fase2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-socket
  template:
    metadata:
      labels:
        app: node-socket
    spec:
      containers:
      - name: node-socket
        image: docker.io/ifigueroa065/api-node-socket:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: node-socket-db-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: node-socket-db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: node-socket-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: node-socket-db-secret
              key: DB_NAME
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: node-socket-service
  namespace: so1-fase2
spec:
  selector:
    app: node-socket
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
